version: "3"
services:
  postgres:
    image: "postgres:9.6"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: odk
      POSTGRES_PASSWORD: odk
      POSTGRES_DATABASE: odk
  mail:
    image: "namshi/smtp"
    environment:
      - MAILNAME=${DOMAIN}
  service:
    build:
      context: .
      dockerfile: service.dockerfile
    depends_on:
      - postgres
      - mail
    volumes:
      - /data/transfer:/data/transfer
    environment:
      - DOMAIN=${DOMAIN}
    command: [ "./wait-for-it.sh", "postgres:5432", "--", "./start-odk.sh" ]
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - service
    environment:
      - SSL_TYPE=${SSL_TYPE}
      - DOMAIN=${DOMAIN}
      - CERTBOT_EMAIL=${SYSADMIN_EMAIL}
    ports:
      - "80:80"
      - "443:443"
volumes:
  transfer:

