blank_issues_enabled: true
contact_links:
  - name: Discuss Central on the ODK Forum
    url: https://forum.getodk.org
    about: Please describe issues you're running into in the Support category, ideas for improvements in the Features category and anything else in the Development category.
